### ISSUE TITLE
Fetch error - possibly due to API change.

### ISSUE THREAD

**Issue by IanCZane** [brandleesee/TerminalStocks#3]
When I run TerminalStocks I get this error message:

`Error fetching stock quotes...`
`http://download.finance.yahoo.com/d/quotes.csv?s=AAPL+C+GOOG+IBM+KO+ORCL+V&f`

I think it's possible that the yahoo finance API may have changed.  This could be an error on my end but I do not believe that to be the case.

**Comment by SeaAeria** [comment]
I too got the same error, the API most likely did change.

**Comment by IanCZane** [comment]
@SeaAeria @gonzoblue I'll work on a fix over the weekend.  I don't know Go at all, so it might be more complicated than I'm expecting, but I should have a pull request up within a week or two.  If @brandleesee doesn't support this repo anymore (which I believe he doesn't considering his lack of response on this issue) I'll link you guys to my fork.

**Comment by brandleesee** [comment]
To note that 
* http://download.finance.yahoo.com/d/quotes.csv?s=%s&f=sl1c1p2oghjkva2r2rdyj3j1
* http://download.finance.yahoo.com/d/quotes.csv
* http://www.gummy-stuff.org/Yahoo-stocks.htm  

are all unreachable including the safe `https://` counterparts (as taken from https://github.com/brandleesee/TerminalStocks/blob/master/yahoo_quotes.go). 

This because of violation of Yahoo's Terms & Conditions and what not. https://stackoverflow.com/questions/44057580/yahoo-finance-api-changes-2017

Therefore, Yahoo's single spreadsheet from which all stocks' data is parsed is not available.

An alternative has to be found, maybe Google's API? Any suggestions?

Furthermore, in absence of the above referenced spreadsheet, all stocks can be quoted **individually** using the new API. However, this, as already mentioned needs code refactoring. I also do not possess the skill to code this in GO language.

Also note that there is v8 of Yahoo's API: 
* https://query1.finance.yahoo.com/v8/finance/chart/GOOG?range=1d&includePrePost=false&interval=2m&corsDomain=finance.yahoo.com&.tsrc=finance
* https://github.com/herval/yahoo-finance/issues/51#issuecomment-344824113

Albeit not in GO language, these may help:
* http://blog.bradlucas.com/posts/2017-06-02-new-yahoo-finance-quote-download-url/
* https://github.com/bradlucas/get-yahoo-quotes/blob/master/get-yahoo-quotes.sh
* https://www.mrexcel.com/forum/excel-questions/1005785-yahoo-finance-api-stock-quotes-changed.html
* https://stackoverflow.com/questions/47064776/has-yahoo-suddenly-today-terminated-its-finance-download-api/47148296#47148296

**Comment by brandleesee** [comment]
Thank you @jamesonjlee 
@IanCZane  @SeaAeria  @gonzoblue can you check whether issue is resolved from your end?
